server:
  port: 8080
  servlet:
    context-path: /security


spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytestdb
    username: root
    password: zhypar_1234


